# Generated by Django 5.1.4 on 2025-01-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('electricity_consumption', models.FloatField()),
                ('gas_consumption', models.FloatField()),
                ('vehicle_count', models.IntegerField()),
                ('resident_count', models.IntegerField()),
                ('waste_production', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('electricity_consumption', models.FloatField()),
                ('fuel_consumption', models.FloatField()),
                ('waste_production', models.FloatField()),
                ('employee_count', models.IntegerField()),
                ('production_volume', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
